# Generated by Django 4.2.19 on 2026-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
