# Generated by Django 4.2.19 on 2026-01-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
