# Generated by Django 4.2.19 on 2026-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField(max_length=500)),
                ('sender_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
